version: "3"

services:
  server:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./app/src:/home/app/src
    depends_on:
      - db
      - rabbitmq
      - worker
    ports:
      - 3000:3000
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - rabbitmq

  db:
    image: postgres:9.4
    volumes:
      - ./database/data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.7
    ports:
      - 5462:5462

  # testserver:
  #   env_file: .env
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/api
  #   depends_on:
  #     - testdb
  #   ports:
  #     - 5053:5053
  #   environment:
  #     APPLICATION_PORT: 5053
  #     APPLICATION_DB_CONTAINER: testdb
  #   command: python -m pytest test/

  # testdb:
  #   image: postgres:9.4
