FROM python:3.7
RUN mkdir -p /home/app/
WORKDIR /home/app/
COPY requirements.txt .
COPY requirements-dev.txt .
RUN pip install --upgrade pip --no-cache-dir -r requirements-dev.txt
COPY . .
CMD ["python", "./app/src/server.py"]